spring:
  application.name: organisation-service
  cloud.kubernetes.reload.enabled: false
  redis:
    host: redis-service
    port: 6379
  rabbitmq:
   host: rabbitmq
   port: 5672
   username: guest
   password: guest
server.port: 8084
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
ribbon:
  http:
    client:
      enabled: false
server.servlet.context-path: /api/organisation-service
client:
  api:
    booking-service: http://booking-service:8081/api/booking-service